# Practica de Algebra lineal

### *Nombre*

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [1]:
# Multiplicación de un vector por un escalar
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

# Suma de dos vectores.
# He añadido el redondeo ya que en algunos casos salian muchos decimales 0's o 9's
def add(v,w):   
    return [round(v[0]+w[0],2),round(v[1]+w[1],2)]

u = [1,2]
v = [3,4]

[add(mult_vector_escalar(float(i)/100,u),v) for i in range(101)]

[[3.0, 4.0],
 [3.01, 4.02],
 [3.02, 4.04],
 [3.03, 4.06],
 [3.04, 4.08],
 [3.05, 4.1],
 [3.06, 4.12],
 [3.07, 4.14],
 [3.08, 4.16],
 [3.09, 4.18],
 [3.1, 4.2],
 [3.11, 4.22],
 [3.12, 4.24],
 [3.13, 4.26],
 [3.14, 4.28],
 [3.15, 4.3],
 [3.16, 4.32],
 [3.17, 4.34],
 [3.18, 4.36],
 [3.19, 4.38],
 [3.2, 4.4],
 [3.21, 4.42],
 [3.22, 4.44],
 [3.23, 4.46],
 [3.24, 4.48],
 [3.25, 4.5],
 [3.26, 4.52],
 [3.27, 4.54],
 [3.28, 4.56],
 [3.29, 4.58],
 [3.3, 4.6],
 [3.31, 4.62],
 [3.32, 4.64],
 [3.33, 4.66],
 [3.34, 4.68],
 [3.35, 4.7],
 [3.36, 4.72],
 [3.37, 4.74],
 [3.38, 4.76],
 [3.39, 4.78],
 [3.4, 4.8],
 [3.41, 4.82],
 [3.42, 4.84],
 [3.43, 4.86],
 [3.44, 4.88],
 [3.45, 4.9],
 [3.46, 4.92],
 [3.47, 4.94],
 [3.48, 4.96],
 [3.49, 4.98],
 [3.5, 5.0],
 [3.51, 5.02],
 [3.52, 5.04],
 [3.53, 5.06],
 [3.54, 5.08],
 [3.55, 5.1],
 [3.56, 5.12],
 [3.57, 5.14],
 [3.58, 5.16],
 [3.59, 5.18],
 [3.6, 5.2],
 [3.61, 5.22],
 [3.62, 5.24],
 [3.63, 5.26],
 [3.64, 5.28],
 [3.65, 5.3],
 [3.66, 5.32],
 [3.67, 5.34],
 

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [2]:
# Función que realiza la operación XOR entre cada de elementos de los dos vectores
def encdec(p,k):
    if len(p) == len(k):
        # Si los dos vectores tienen la misma longitud, hacemos una XOR de cada elemento
        return [p[i] ^ k[i] for i in range(len(p))]

In [3]:
# Probamos la función
p = [0,0,0,1,1,1,0,1,0,1] 
k = [0,1,0,0,1,0,1,0,1,0] 

print("Palabra original: ",p)

enc = encdec(p,k)
print("Palabra encriptada con la clave k: ",enc)

dec = encdec(enc,k)
print("Palabra decodificada con la clave k: ",dec)

if p == dec:
    print("¡¡ YUPI !!! La palabra original coincide con la que se ha decodificado.")
else:
    print("!! HUSTON WE HAVE A PROBLEM !!")

('Palabra original: ', [0, 0, 0, 1, 1, 1, 0, 1, 0, 1])
('Palabra encriptada con la clave k: ', [0, 1, 0, 1, 0, 1, 1, 1, 1, 1])
('Palabra decodificada con la clave k: ', [0, 0, 0, 1, 1, 1, 0, 1, 0, 1])
¡¡ YUPI !!! La palabra original coincide con la que se ha decodificado.


<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [4]:
# Multiplicación de dos vectores de cualquier longitud
def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in range(len(u)))

In [5]:
D = {"lupulo", "malta", "agua", "levadura"} 
coste = [2.5,1.5,0.006,0.45]
cantidad = [6,14,7,11]
coste = producto_vectorial(coste,cantidad)
print("El coste de nuestra cerveca es: ",round(coste,2))

('El coste de nuestra cerveca es: ', 40.99)


<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [6]:
# Suma tres vectores de cualquier longitud
def addn(u,v,w):
    return[u[i] + v[i]+w[i] for i in range(len(v))]

# Producto de un escalar por un vector
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [7]:
v1 = [3,0,0]
u1 = [2,0,1]
u2 = [1,0,2]
u3 = [2,2,2]
# [3,0,0] como combinación lineal de [2,0,1],[1,0,2],[2,2,2], es decir:
# v1 = c1*u1 + c2*u2 + c3*u3
# Tenemos un sistema de 3 ecuaciones con 3 incóginitas
# 3 = 2c1 + c2 +2c3
# 0 = 2c3
# 0 = c1 + 2c2 + 2c3
# Resolviendo el sistema tenemos los coeficientes [2,-1,0]

coef = [2,-1,0]
resultado = addn(mult_vector_escalar(coef[0],u1),
          mult_vector_escalar(coef[1],u2),
          mult_vector_escalar(coef[2],u3))

assert v1 == resultado,"Resultado erroneo"
resultado

[3, 0, 0]

In [8]:
v2 = [0,2,0]

# [0,2,0] como combinación lineal de [2,0,1],[1,0,2],[2,2,2], es decir:
# v1 = c1*u1 + c2*u2 + c3*u3
# Tenemos un sistema de 3 ecuaciones con 3 incóginitas
# 0 = 2c1 + c2 +2c3
# 2 = 2c3
# 0 = c1 + 2c2 + 2c3
# Resolviendo el sistema tenemos los coeficientes [-2/3,-2/3,1]

coef = [-2/3.0,-2/3.0,1]

resultado = addn(mult_vector_escalar(coef[0],u1),
          mult_vector_escalar(coef[1],u2),
          mult_vector_escalar(coef[2],u3))

assert v2 == resultado,"Resultado erroneo"
resultado

[0.0, 2.0, 0.0]

In [9]:
v3 = [0,0,1]

# [0,0,1] como combinación lineal de [2,0,1],[1,0,2],[2,2,2], es decir:
# v1 = c1*u1 + c2*u2 + c3*u3
# Tenemos un sistema de 3 ecuaciones con 3 incóginitas
# 0 = 2c1 + c2 +2c3
# 0 = 2c3
# 1 = c1 + 2c2 + 2c3
# Resolviendo el sistema tenemos los coeficientes [-1/3,2/3,0]

coef = [-1/3.0,2/3.0,0]
resultado = addn(mult_vector_escalar(coef[0],u1),
          mult_vector_escalar(coef[1],u2),
          mult_vector_escalar(coef[2],u3))

assert v3 == resultado,"Resultado erroneo"
resultado

[0.0, 0.0, 1.0]

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [10]:
import numpy as np

A = np.matrix([
    [2,-3],
    [-4,6]
])
B = np.matrix([
    [8,4],
    [5,5]
])
C = np.matrix([
    [5,-2],
    [3,1]
])

A*B

matrix([[ 1, -7],
        [-2, 14]])

In [11]:
A*C

matrix([[ 1, -7],
        [-2, 14]])

Vemos que A*B = A*C de todas formas lo comprobamos

In [12]:
np.array_equal(A*B,A*C)

True

Comprobamos tambien que B ≠ C

In [13]:
np.array_equal(B,C)

False

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [14]:
A = np.matrix([
    [3,-6],
    [-1,2]
])

B = np.matrix([
    [2,2],
    [1,1]
])

A * B

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [15]:
def sarrus_det3(a):
    # nos aseguramos que "a" es 3x3
    if a.shape == (3,3):
        sum1 = a[0,0]*a[1,1]*a[2,2] + a[0,1]*a[1,2]*a[2,0] + a[0,2]*a[1,0]*a[2,1]
        sum2 = a[0,2]*a[1,1]*a[2,0] + a[0,1]*a[1,0]*a[2,2] + a[0,0]*a[1,2]*a[2,1]
        return sum1 - sum2

Comprobaremos que funciona con 100 matrices aleatorias de enteros entre -100 y 100

In [16]:
for i in range(100):
    random_matrix = np.random.randint(-100,100,(3,3))
    
    sarrus_det = sarrus_det3(random_matrix)
    np_det     = round(np.linalg.det(random_matrix))
    
    assert sarrus_det == np_det, "Errooooooooor"
print "Prueba OK"

Prueba OK


<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [17]:
import numpy as np

def soluciones(A,A_amp):
    rangoA = np.linalg.matrix_rank(A)
    rangoA_amp = np.linalg.matrix_rank(A_amp)
    n = A.shape[1] # Número de variables
    if rangoA == rangoA_amp:
        if rangoA == n:
            print("Sistema compatible determinado -> 1 Solución")
        else:
            print("Sistema compatible indeterminado -> Infinitas soluciones")
    else:
        print("Sistema incompatible. No tiene solucion")

A = np.matrix([
    [1,-2,1],
    [0,2,-8],
    [-4,5,9]
])
A_amp = np.matrix([
    [1,-2,1,0],
    [0,2,-8,8],
    [-4,5,9,9]
])
soluciones(A,A_amp)

Sistema compatible determinado -> 1 Solución


> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [18]:
A = np.matrix([
    [0,1,-4],
    [2,-3,2],
    [5,-8,7]
])
A_amp = np.matrix([
    [0,1,-4,8],
    [2,-3,2,1],
    [5,-8,7,1]
])
soluciones(A,A_amp)

Sistema incompatible. No tiene solucion


> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [19]:
A = np.matrix([
    [1,0,1],
    [2,3,1],
    [3,3,2]
])
A_amp = np.matrix([
    [1,0,1,2],
    [2,3,1,3],
    [3,3,2,5]
])
soluciones(A,A_amp)

Sistema compatible indeterminado -> Infinitas soluciones


<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

Sabemos que:   

r([x , y ]) = $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  x\\
  y\\
  \end{array} } \right]$

Para que sea una función lineal debe cumplir:  
* Para cada vector v en V y cada escalar α en F, f (αv) = αf(v)  
* Por cada dos vectores u y v en V, f (u + v) = f (u) + f (v)  

Veamos cada punto:  
* r(α[x,y]) = $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ α $\left[ {\begin{array}{cc}
  x\\
  y\\
  \end{array} } \right]$ =  $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  αx\\
  αy\\
  \end{array} } \right]$  =
   $\left[ {\begin{array}{cc}
   αxcos\theta -αysin\theta \\
   αxsin\theta +αycos\theta \\
  \end{array} } \right]$ =
  α $\left[ {\begin{array}{cc}
   xcos\theta -ysin\theta \\
   xsin\theta +ycos\theta \\
  \end{array} } \right]$ =  
  = α $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  x\\
  y\\
  \end{array} } \right]$ =
  α r([x,y])  
  
  
* r([x,y] + [z,t]) = $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  x + z\\
  y + t\\
  \end{array} } \right]$  =
   $\left[ {\begin{array}{cc}
   xcos\theta +zcos\theta -ysin\theta-tsin\theta \\
   xsin\theta+zsin\theta + ycos\theta+tcos\theta  \\
  \end{array} } \right]$ =
   $\left[ {\begin{array}{cc}
   xcos\theta -ysin\theta \\
   xsin\theta +ycos\theta \\
  \end{array} } \right]$ +
   $\left[ {\begin{array}{cc}
   zcos\theta -tsin\theta \\
   zsin\theta +tcos\theta  \\
  \end{array} } \right]$ =

  =$\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  x\\
  y\\
  \end{array} } \right]$ +
  $\left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]$ ∗ $\left[ {\begin{array}{cc}
  z\\
  t\\
  \end{array} } \right]$ = r([x,y]) + r([z,t])



<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

Se trata de resolver A * X = B siendo:

A = $\left[ {\begin{array}{cc}
   2 & 1 & 0 \\
   2 & 0 & 1 \\
   2 & -1 & 0 \\
   3 & 0 & 1 \\   
   \end{array} } \right]$      y
B = $\left[ {\begin{array}{cc}
   6 \\
   3 \\
   2 \\
   5 \\   
  \end{array} } \right]$  
  
Si la matriz A fuese invertible podríamos hacer X = A<sup>-1</sup>B , pero como no es cuadrada no es invertible y tendremos que resolverlo de otra manera.  
Por la misma razón no funciona el solve de la libreria linalg.  
La forma mas rápida usando python seria con la libreria sympy de la siguiente manera

In [20]:
import numpy as np
from sympy import Symbol, solve

A = np.matrix([
    [2,1,0],
    [2,0,1],
    [2,-1,0],
    [3,0,1]
])

B = np.matrix([
    [6],
    [3],
    [2],
    [5]
])

A_amp = np.matrix([
    [2,1,0,6],
    [2,0,1,3],
    [2,-1,0,2],
    [3,0,1,5]
])
# Miramos si tiene soluciones
soluciones(A,A_amp)

# Como tiene solución, la buscamos con sympy
x=Symbol('x')
y=Symbol('y')
z=Symbol('z')
s =solve([2*x+y-6,
          2*x+z-3,
          2*x-y-2,
          3*x+z-5],
          [x,y,z]
         )
print 'La solucion es:',s

# Comprobamos que realmente obtenemos el vector [6,3,2,5]
s[x]*np.array([2,2,2,3]) + s[y] * np.array([1,0,-1,0]) + s[z] * np.array([0,1,0,1])

Sistema compatible determinado -> 1 Solución
La solucion es: {x: 2, z: -1, y: 2}


array([6, 3, 2, 5], dtype=object)

Por tanto la representación en coordenadas de v en terminos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1] es [2,2,-1] ya que 2[2, 2, 2, 3] + 2[1, 0, −1, 0] - 1[0, 1, 0, 1] = [6, 3, 2, 5]


<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

![No se puede mostrar](Images/grafoCiudades.jpg)  

** Algoritmo Grow**  
Colocamos las aristas en orden creciente según sus pesos: 2,7,9  
Cogemos la arista {Pembroke Campus, Bio Med} y la añadimos a S.  
Hay que añadir el nodo Athletic Complex. Lo podemos hacer de dos maneras:
   * {Pembroke Campus,Athletic Complex} con un peso de 7  
   * {Bio Med, Athletic Complex} con un peso de 9  
Escogemos el de menor peso {Pembroke Campus,Athletic Complex} y lo añadimos a S.  
Como ya tenemos todos los nodos ya hemos terminado y tenemos un peso final de **2 + 7 = 9**


** Algoritmo Shrink**   
Colocamos las aristas en orden decreciente según sus pesos: 9,7,2  
La arista que mas peso tiene es {Bio Med, Athletic Campus}  
Si la quitamos aun podemos ir de Bio Med a Athletic Campus (pasando por Pembroke Campus)  
Nos queda por tanto S = {{Pembroke Campus, Bio Med},{Pembroke Campus, Athletic Campus}}  
No se puede eliminar ninguna otra arista, por tanto nos queda un peso de **2 + 7 = 9**


<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [21]:
import numpy as np

M = np.matrix([
    [1,0,0,5],
    [0,2,0,7],
    [0,0,3,9]
])
M_trans = np.transpose(M)

rango_filas_M = np.linalg.matrix_rank(M)
rango_columnas_M = np.linalg.matrix_rank(M_trans)

print 'El rango por filas de M es: ', rango_filas_M
print 'El rango por columndas de M es: ', rango_columnas_M

El rango por filas de M es:  3
El rango por columndas de M es:  3


<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

Si usamos arrays de numpy, para hacer el producto escalar de dos vectores debemos usar la función **dot**

In [22]:
def proyeccion_paralela(b, a):
    aa = np.dot(a,a.T)
    sigma = np.dot(a,b.T)/float(aa) if aa > 10^-20 else 0
    #print sigma
    return [sigma * a[i] for i in range(len(a))]

def proyeccion_ortogonal(b, a):
    return b - proyeccion_paralela(b, a)

In [23]:
import numpy as np
a=np.array([6,2])
b=np.array([2,4])
p = proyeccion_paralela(b,a)

print 'El punto mas cercano a b es [',p[0],',',p[1],']'
print 'La distancia a b es: ',np.linalg.norm(proyeccion_ortogonal(b,a))

El punto mas cercano a b es [ 3.0 , 1.0 ]
La distancia a b es:  3.16227766017


<span style="color:blue">Comentarios sobre el módulo</style>

Aunque este modulo es eminentemente teórico (y creo que la teoria es muy necesaria), echo en falta relacionarlo de alguna manera con casos prácticos orientados al análisis de datos.  
Supongo que el módulo es muy básico y debe ser difícil relacionarlo con un caso práctico, pero creo que esto nos motivaria un poco,si no, te quedas un poco como diciendo "OK he repasado el algebra de BUP o COU, y?"

Entiendo que esto son las bases para cosas como la regresión y el deep learning que supongo veremos mas adelante, pero no estaría demás dar unas pinceladas. Si tenemos miedo de hacer que el contenido de los módulos se solapen, entonces en mi opinión quedan demasiado inconexos.

Por otro lado, el hecho de explicarlo con los notebooks está muy bien pero hecho en falta algún tipo de pizarra donde el profesor pudiese escribir, dibujar, resaltar cosas para aclarar mejor los conceptos y ser más ágiles.

De todas formas, para el "rollo" teórico que ha sido, lo has hecho bastante ameno. Gracias!
